(add-to-list 'exec-path (concat (getenv "HOME") "/.cabal/bin"))
(add-to-list 'interpreter-mode-alist '("runhaskell" . haskell-mode))


(defun my/haskell-mode-hook ()
  (ghc-init)
  (add-to-list 'ac-sources 'ac-source-ghc-mod)
  (setq flycheck-checker 'haskell-ghc)
  (turn-on-haskell-doc-mode)
  ;; (haskell-simple-indent-mode)
  (haskell-indent-mode)
  (define-key haskell-mode-map (kbd "TAB") 'haskell-simple-indent)
  (define-key haskell-mode-map (kbd "<backtab>") 'haskell-simple-indent-backtab)
  (define-key haskell-mode-map (kbd "M-n") 'forward-paragraph)
  (define-key haskell-mode-map (kbd "M-p") 'backward-paragraph)
  (define-key haskell-mode-map (kbd "S-TAB") 'haskell-simple-indent-backtab)
  (define-key haskell-mode-map [remap newline] 'haskell-simple-indent-newline-same-col)
  (define-key haskell-mode-map [remap newline-and-indent] 'haskell-simple-indent-newline-indent))

(add-hook 'haskell-mode-hook 'my/haskell-mode-hook)
